# https://taskfile.dev
version: '3'

vars:
  ROOT_DIR: .

tasks:
  run-dev:
    desc: Runs the planner app in develop environment with (default db is sqlite)
    dir: "{{.ROOT_DIR}}"
    cmds:
      - pwsh -Command "Write-Host 'Starting development environment...'"
      - pwsh -File ./runApp.ps1 -env dev
  
  run-dev-mysql:
    desc: Runs the planner app in develop environment with mysql db
    dir: "{{.ROOT_DIR}}"
    cmds:
      - pwsh -Command "Write-Host 'Starting development environment with MySQL...'"
      - pwsh -File ./runApp.ps1 -env dev -rdbms mysql

  open-prod-mysql-db:
    desc: Opens the dockerised MySQL database in production environment. Note you will be prompted for the db password (see ./b/.env). 
    dir: "{{.ROOT_DIR}}"
    cmds:
      - docker exec -it app-mysql mysql -u root -p planner_app_db