name: Deploy Flask Backend to Azure Web App

on:
  workflow_dispatch:
  push:
    branches: ["main"] 
    paths:
      - 'b/**'

env:
    web_app_name: plannerAppBackendNC
    python_version: 3.12

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python: Download python
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ env.python_version }} 

      # Step 3: install python venv in linux 
      - name: Install Python vevn
        run: sudo apt install python${{ env.python_version }}-venv -y

      # Step 4: create and activate venv, then install python dependencies
      - name: Install dependencies
        working-directory: b/
        run: |
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 5: Run unit tests 
      - name: Run unit tests
        env:
          accessTokenDurationMins: ${{ secrets.ACCESSTOKENDURATIONMINS }}
          refreshTokenDurationDays: ${{ secrets.REFRESHTOKENDURATIONDAYS }}
          expired_bespoke_session_cookie: ${{ secrets.EXPIRED_BESPOKE_SESSION_COOKIE }}
          expired_access_token_cookie: ${{ secrets.EXPIRED_ACCESS_TOKEN_COOKIE }}
          azureTenantId: ${{ secrets.AZURETENANTID }}
          kvClientId: ${{ secrets.KVCLIENTID }}
          kvClientSecret: ${{ secrets.KVCLIENTSECRET }}
          project_title_limit: 80
          objective_title_limit: 80
          task_description_limit: 200
        working-directory: b/
        run: |
          source .venv/bin/activate
          python -m unittest discover

      # Step6: Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.web_app_name }}
          slot-name: 'production'
          package: 'b/'
          publish-profile: ${{ secrets.AZURE_WEB_APP_PUBLISH_PROFILE_FOR_PLANNER_APP }}