name: Deploy React Frontend to Azure Static Web App

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths: ["f/**"]

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: false
          lfs: false
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_LIVELY_MEADOW_088461003 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "./f"
          output_location: "dist"
        env:
          VITE_BACKEND_API_URL: ${{ secrets.VITE_BACKEND_NC_API_URL }}